<Project>
	<Import Project="$(MSBuildThisFileDirectory)local.props" Condition="Exists('$(MSBuildThisFileDirectory)local.props')" />
	<PropertyGroup>
		<DuckovPath Condition="'$(DuckovPath)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Escape from Duckov\Duckov_Data</DuckovPath>
	</PropertyGroup>
</Project>
